#pragma once

#define DISABLE_POWER_ON_COUNT

#if defined(PLATFORM_ESP32) || defined(PLATFORM_ESP32_C3) || defined(PLATFORM_ESP32_C3)

#ifndef BUILD_I2C_WIRE
#define BUILD_I2C_WIRE
#endif
#ifndef BUILD_EEPROM_EXPORT_IMPORT
#define BUILD_EEPROM_EXPORT_IMPORT
#endif
#ifndef BUILD_CUSTOM_MIXER
#define BUILD_CUSTOM_MIXER
#endif
#ifndef BUILD_WEB_BACKEND_WEBSOCKET
#define BUILD_WEB_BACKEND_WEBSOCKET
#endif
#ifndef BUILD_VESC_UART
#define BUILD_VESC_UART
#endif
#ifndef BUILD_AM32_CONFIG
#define BUILD_AM32_CONFIG
#endif
#ifndef BUILD_SERVOS_MOVE_BLINK
#define BUILD_SERVOS_MOVE_BLINK
#endif
#ifndef ENABLE_AM32_TCP_BRIDGE
#define ENABLE_AM32_TCP_BRIDGE
#endif
#ifndef ENABLE_VESC_TELEMETRY
#define ENABLE_VESC_TELEMETRY
#endif
#ifndef ENABLE_VESC_TCP_BRIDGE
#define ENABLE_VESC_TCP_BRIDGE
#endif

#endif

#if defined(PLATFORM_ESP8266)

#ifndef BUILD_DISABLE_RGB_LED
#define BUILD_DISABLE_RGB_LED
#endif
#ifndef BUILD_EEPROM_EXPORT_IMPORT
#define BUILD_EEPROM_EXPORT_IMPORT
#endif
#ifndef BUILD_CUSTOM_MIXER
#define BUILD_CUSTOM_MIXER
#endif
#ifndef BUILD_WEB_BACKEND_WEBSOCKET
#define BUILD_WEB_BACKEND_WEBSOCKET
#endif
#ifndef BUILD_SERVOS_MOVE_BLINK
#define BUILD_SERVOS_MOVE_BLINK
#endif

#endif

#if !defined(BUILD_SHREW_UNNECESSARY) && defined(PLATFORM_ESP8266) && defined(TARGET_RX)
#define TRIM_UNNECESSARY_HW // saves about 1KB after compression
#endif

#if defined(USE_VESC_UART) && !defined(BUILD_VESC_UART)
#define BUILD_VESC_UART
#endif
